<?php

namespace App\DataFixtures;

use App\Entity\Article;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class AppFixtures extends Fixture
{
    public function load(ObjectManager $manager)
{
  $article1 = new Article();
     $article1
    ->setTitle("Cake au Carotte")
    ->setDescript("Le gâteau aux carottes est un dessert moelleux et épicé, riche en saveurs grâce à l'ajout de carottes râpées, de noix, et d'un mélange d'épices comme la cannelle, la muscade et le gingembre. Ce gâteau est souvent couronné d'un glaçage crémeux au fromage à la crème, ce qui en fait un régal pour les occasions spéciales ou juste pour le plaisir quotidien. Voici une recette simple pour faire un gâteau aux carottes délicieux et moelleux.")
    ->setPicture("Carrot.webp")
    ->setIngredient("Ingrédients : 2 tasses (250g) de farine tout usage, 2 cuillères à café de poudre à lever, 1/2 cuillère à café de bicarbonate de soude, 1/2 cuillère à café de sel, 1 et 1/2 cuillères à café de cannelle moulue, 1/2 cuillère à café de muscade moulue, 1/4 cuillère à café de gingembre moulu, 4 œufs, 1 tasse (200g) de sucre brun, 1 tasse (200g) de sucre blanc, 1 tasse (240ml) d'huile végétale, 2 cuillères à café d'extrait de vanille, 3 tasses (300g) de carottes râpées,1 tasse (100g) de noix hachées.")
    ->setPreparation("Instructions : Préchauffer le four et préparer le moule : Préchauffez votre four à 350°F (175°C). Graissez et farinez deux moules ronds de 9 pouces. Mélanger les ingrédients secs : Dans un grand bol, mélangez la farine, la poudre à lever, le bicarbonate de soude, le sel, la cannelle, la muscade et le gingembre. Battre les œufs et les sucres : Dans un autre grand bol, battez les œufs, le sucre brun et le sucre blanc jusqu'à ce que le mélange soit homogène. Ajoutez l'huile et la vanille, et continuez à battre jusqu'à ce que le tout soit bien mélangé. Ajouter les ingrédients secs : Incorporez progressivement les ingrédients secs au mélange d'œufs jusqu'à ce que tout soit bien combiné. Incorporer les carottes et les noix : Ajoutez les carottes râpées et les noix hachées, et mélangez bien. Cuire : Versez la pâte dans les moules préparés et lissez le dessus. Cuisez au four pendant 25 à 30 minutes ou jusqu'à ce qu'un cure-dent inséré au centre en ressorte propre. Préparer le glaçage : Pendant que le gâteau refroidit, battez le beurre et le fromage à la crème ensemble jusqu'à ce qu'ils soient légers et mousseux. Ajoutez progressivement le sucre glace et la vanille, et continuez à battre jusqu'à ce que le glaçage soit lisse. Garnir le gâteau : Une fois les gâteaux complètement refroidis, étalez une couche de glaçage sur le premier gâteau, placez le deuxième gâteau par-dessus, puis recouvrez tout le gâteau avec le reste du glaçage.")
    ->setContent("Ce gâteau aux carottes est parfait pour célébrer toute occasion spéciale ou pour offrir un goûter réconfortant. Il est encore meilleur le lendemain, les saveurs ayant eu le temps de se mélanger davantage.");
    
    $article2 = new Article();
    $article2
    ->setTitle("Cake Rhubarbe Amande.")
    ->setDescript("Le gâteau rhubarbe-amande est un dessert délicieusement équilibré qui combine la légère acidité de la rhubarbe avec la douceur des amandes. Ce gâteau tendre et moelleux est souvent agrémenté de morceaux de rhubarbe et garni d'une couche croustillante d'amandes effilées, offrant ainsi un contraste parfait de textures et de saveurs. Voici une recette facile pour préparer un gâteau rhubarbe-amande à la maison.")
    ->setPicture("rhubarbe.webp")
    ->setIngredient("Ingrédients : 1 tasse (150g) de rhubarbe fraîche, coupée en petits morceaux, 1 cuillère à soupe de sucre, pour saupoudrer sur la rhubarbe, 1/2 tasse (115g) de beurre, 3/4 tasse (150g) de sucre, 2 œufs, 1 cuillère à café d'extrait de vanille, 1/2 cuillère à café d'extrait d'amande, 1/2 tasse (180g) de farine tout usage, 1/2 cuillère à café de levure chimique, 1/2 cuillère à café de bicarbonate de soude, 1/4 cuillère à café de sel, 1/2 tasse (120ml) de crème aigre ou de yaourt nature, 1/2 tasse (50g) d'amandes effilées.")
    ->setPreparation("Instructions : Préparation de la rhubarbe : Préchauffez votre four à 350°F (175°C). Mélangez la rhubarbe coupée avec une cuillère à soupe de sucre et réservez pour qu'elle dégage un peu de son jus. Préparer la pâte : Dans un grand bol, créez un mélange crémeux en battant le beurre et le sucre. Incorporez les œufs un à un, puis ajoutez les extraits de vanille et d'amande. Mélanger les ingrédients secs : Dans un autre bol, tamisez ensemble la farine, la levure chimique, le bicarbonate de soude, et le sel. Combiner les mélanges : Ajoutez alternativement les ingrédients secs et la crème aigre au mélange de beurre, en commençant et en terminant par les ingrédients secs. Ajouter la rhubarbe : Incorporez délicatement la rhubarbe préparée. Préparer le moule et cuire : Versez la pâte dans un moule à gâteau graissé et fariné. Saupoudrez le dessus du gâteau avec les amandes effilées. Cuisez au four pendant environ 45 minutes ou jusqu'à ce qu'un cure-dent inséré au centre en ressorte propre. Refroidir et servir : Laissez refroidir le gâteau dans le moule sur une grille pendant 10 minutes, puis démoulez et laissez refroidir complètement. Servez tel quel ou avec une légère saupoudrée de sucre glace.")
    ->setContent("Ce gâteau rhubarbe-amande est idéal pour un dessert de printemps ou d'été, profitant pleinement de la saisonnalité de la rhubarbe. Il peut être servi à l'heure du thé ou comme dessert après un repas.");

    $article3 = new Article();
    $article3
    ->setTitle("Compote de Poire.")
    ->setDescript("La compote de poire est un dessert doux et velouté qui met en valeur la délicate saveur des poires. Pour préparer ce dessert simple mais délicieux, vous aurez besoin de poires mûres, d'un peu de sucre pour rehausser leur douceur naturelle, et d'une touche de vanille ou de cannelle pour ajouter une dimension aromatique. Voici une recette facile pour faire de la compote de poire à la maison.")
    ->setPicture("poire.webp")
    ->setIngredient("Ingrédients : 6 poires mûres, 1/4 de tasse de sucre (ajustez selon la douceur des poires), 1/2 tasse d'eau, 1 gousse de vanille ou 1 cuillère à café d'extrait de vanille, 1/2 cuillère à café de cannelle en poudre (facultatif).")
    ->setPreparation("Instructions : Préparer les poires : Pelez les poires, retirez les cœurs et les pépins, puis coupez-les en petits morceaux. Cuire les poires : Dans une casserole, combinez les morceaux de poire, le sucre, l'eau, et les graines de la gousse de vanille (ou l'extrait de vanille). Si vous utilisez de la cannelle, ajoutez-la également à ce stade. Mijoter : Portez à ébullition, puis baissez le feu et laissez mijoter doucement pendant environ 20 minutes, ou jusqu'à ce que les poires soient très tendres. Mixer (facultatif) : Pour une compote lisse, passez le mélange au mixeur ou utilisez un mixeur plongeant directement dans la casserole. Si vous préférez une texture plus rustique, écrasez simplement les poires à la fourchette. Ajuster la consistance : Si la compote est trop épaisse, ajoutez un peu d'eau pour obtenir la consistance désirée. Si elle est trop liquide, laissez cuire quelques minutes supplémentaires à feu doux. Refroidir et servir : Laissez refroidir la compote avant de servir. Elle peut être servie tiède ou froide, selon votre préférence.")
    ->setContent("Cette compote de poire est excellente servie seule, mais elle peut également accompagner du yaourt, du porridge ou des crêpes pour un petit-déjeuner ou un dessert léger et satisfaisant.");

    $article4 = new Article();
    $article4
    ->setTitle("Cake noisette et zeste de citron.")
    ->setDescript("Le gâteau noisette et zeste de citron est un dessert léger et aromatique qui marie la richesse des noisettes avec la fraîcheur vivifiante du citron. Ce gâteau moelleux est parfait pour une collation après-midi ou un dessert délicat. Voici une recette simple pour préparer ce gâteau chez vous.")
    ->setPicture("noisette.webp")
    ->setIngredient("Ingrédients : 1/2 tasses (180g) de farine tout usage, 1/2 tasse (60g) de poudre de noisettes, 2 cuillères à café de levure chimique, 1/4 cuillère à café de sel, 3/4 tasse (170g) de beurre, à température ambiante, 1 tasse (200g) de sucre, 3 œufs, Zeste de 2 citrons, 1/4 tasse (60ml) de jus de citron, 1/2 cuillère à café d'extrait de vanille, 1/2 tasse (120ml) de lait.")
    ->setPreparation("Instructions : Préparation : Préchauffez votre four à 350°F (175°C). Graissez et farinez un moule à cake. Mélanger les ingrédients secs : Dans un bol, mélangez la farine, la poudre de noisettes, la levure chimique et le sel. Battre le beurre et le sucre : Dans un grand bol, battez le beurre avec le sucre jusqu'à ce que le mélange soit léger et mousseux. Ajoutez les œufs un à un, en battant bien après chaque ajout. Ajouter les zestes et les liquides : Incorporez le zeste de citron et l'extrait de vanille. Ajoutez alternativement les ingrédients secs et le lait à la préparation, en commençant et en terminant par les ingrédients secs. Mélangez jusqu'à ce que tout soit juste combiné, sans trop travailler la pâte. Cuisson : Versez la pâte dans le moule préparé et lissez le dessus. Cuire au four pendant 45 à 55 minutes ou jusqu'à ce qu'un cure-dent inséré au centre en ressorte propre. Préparer le glaçage : Pendant que le gâteau refroidit, mélangez le sucre glace avec suffisamment de jus de citron pour obtenir un glaçage épais mais encore coulant. Finir le gâteau : Une fois le gâteau complètement refroidi, démoulez-le et versez le glaçage sur le dessus, en laissant couler légèrement sur les côtés.")
    ->setContent("Ce gâteau noisette et zeste de citron est exquis servi tel quel ou accompagné d'une tasse de thé ou de café. Son goût raffiné de noisette avec la touche acidulée du citron en fait une excellente option pour toutes sortes d'occasions");

    $article5 = new Article();
    $article5
    ->setTitle("Céleri et betteraves fermentées.")
    ->setDescript("La fermentation est une méthode traditionnelle qui non seulement conserve les légumes mais améliore également leur saveur et leur valeur nutritive. Fermenter du céleri et des betteraves ensemble crée un mélange coloré et nutritif, riche en probiotiques. Voici une recette simple pour faire du céleri et des betteraves fermentées à la maison.")
    ->setPicture("betteraves.webp")
    ->setIngredient("Ingrédients : 1 grosse betterave rouge, pelée et coupée en bâtonnets, 3 tiges de céleri, coupées en bâtonnets, 1 litre d'eau, 2 cuillères à soupe de sel marin non iodé.")
    ->setPreparation("Instructions : Préparer la saumure : Dissolvez le sel dans l'eau pour créer une saumure. Assurez-vous que le sel est complètement dissous. Remplir le bocal : Placez les bâtonnets de betterave et de céleri dans le bocal en verre stérilisé. Essayez de les disposer de manière compacte pour réduire l'espace où l'air pourrait se loger. Verser la saumure : Versez la saumure sur les légumes, en vous assurant qu'ils sont complètement submergés. Laissez environ 2,5 cm (1 pouce) d'espace libre au sommet du bocal. Peser les légumes : Pour garder les légumes submergés, placez un petit sac en plastique rempli de saumure supplémentaire au-dessus. Cela agira comme un poids, et en utilisant de la saumure, vous éviterez de contaminer votre préparation si le sac venait à fuir. Fermer et fermenter : Fermez le bocal avec son couvercle mais pas hermétiquement, car les gaz doivent pouvoir s'échapper. Si votre couvercle est hermétique, ouvrez-le légèrement chaque jour pour libérer la pression. Stockage : Conservez le bocal à température ambiante, à l'abri de la lumière directe du soleil, pendant environ 1 à 2 semaines. La durée exacte dépendra de la température de votre pièce et de vos préférences en matière de goût et de texture. Goûtez régulièrement après le premier jour pour déterminer quand la fermentation a atteint le niveau de saveur désiré. Réfrigération : Une fois la fermentation terminée à votre goût, serrez le couvercle et transférez le bocal au réfrigérateur pour ralentir le processus de fermentation. Les légumes fermentés se conservent bien pendant plusieurs mois au réfrigérateur.")
    ->setContent("Cette préparation de céleri et betteraves fermentées est excellente pour ajouter une touche de couleur et de saveur probiotique à vos repas. Vous pouvez les utiliser comme garniture sur des salades, dans des sandwiches, ou simplement les savourer seuls en snack santé.");

    $article6 = new Article();
    $article6
    ->setTitle("Muffins géants au chocolat.")
    ->setDescript("Voici une recette pour préparer de délicieux muffins géants au chocolat, parfaits pour satisfaire les amateurs de douceurs chocolatées. Ils sont idéaux pour un goûter gourmand ou pour une pause café réconfortante.")
    ->setPicture("Muffins.webp")
    ->setIngredient("Ingrédients : 250 g de farine tout usage, 50 g de cacao en poudre non sucré, 2 cuillères à café de levure chimique, 1/2 cuillère à café de bicarbonate de soude, 1/2 cuillère à café de sel, 150 g de sucre, 100 g de pépites de chocolat noir, 240 ml de lait, 120 ml d'huile végétale, 2 gros œufs, 1 cuillère à café d'extrait de vanille.")
    ->setPreparation("Préparation : Préchauffez le four : Commencez par préchauffer votre four à 200°C (400°F). Graissez les moules à muffins géants ou utilisez des caissettes en papier pour éviter que les muffins n'adhèrent. Mélange des ingrédients secs : Dans un grand bol, tamisez ensemble la farine, le cacao en poudre, la levure chimique, le bicarbonate de soude, et le sel. Ajoutez le sucre et les pépites de chocolat, puis mélangez bien. Mélange des ingrédients liquides : Dans un autre bol, mélangez le lait, l'huile végétale, les œufs et l'extrait de vanille. Assurez-vous que tout est bien combiné. Combinaison des ingrédients : Versez les ingrédients liquides sur les ingrédients secs. Mélangez le tout avec une spatule jusqu'à ce que la pâte soit juste combinée. Évitez de trop mélanger pour ne pas obtenir des muffins trop denses. Remplissage des moules : Répartissez la pâte dans les moules à muffins préparés, remplissant chaque moule jusqu'au 3/4 pour permettre à la pâte de lever. Cuisson : Enfournez les muffins et laissez cuire pendant environ 20-25 minutes, ou jusqu'à ce qu'un cure-dent inséré au centre d'un muffin en ressorte propre. Refroidissement : Laissez les muffins refroidir dans le moule pendant 5 minutes, puis transférez-les sur une grille pour qu'ils refroidissent complètement.")
    ->setContent("Servez ces muffins géants au chocolat seuls ou accompagnés d'un verre de lait froid, d'un café ou d'un thé. Ils sont également délicieux tièdes, avec une boule de glace à la vanille pour une touche extra gourmande.");

    $article7 = new Article();
    $article7
    ->setTitle("Tartinade Courgettes et Persil.")
    ->setDescript("Une tartinade de courgettes et persil est une préparation fraîche et légère, idéale pour être servie sur du pain grillé ou comme dip pour des crudités. Voici une recette simple et savoureuse pour réaliser cette tartinade.")
    ->setPicture("courgette.webp")
    ->setIngredient("Ingrédients : 2 courgettes moyennes, coupées en dés, 1 gousse d'ail, émincée, 1/2 tasse de persil frais, haché, 2 cuillères à soupe d'huile d'olive, Le jus d'1/2 citron, Sel et poivre au goût, 1/4 de tasse de noix ou de pignons de pin (facultatif, pour ajouter du croquant), 1/4 de tasse de parmesan râpé ou de fromage de chèvre frais (facultatif, pour la richesse).")
    ->setPreparation("Instructions : Cuire les courgettes : Chauffez une cuillère à soupe d'huile d'olive dans une poêle à feu moyen. Ajoutez les courgettes et l'ail émincé. Faites sauter jusqu'à ce que les courgettes soient tendres et légèrement dorées, environ 10 minutes. Assaisonnez de sel et de poivre durant la cuisson. Préparer les autres ingrédients : Pendant que les courgettes cuisent, placez le persil, le jus de citron, et l'huile d'olive restante dans un robot culinaire ou un mixeur. Si vous utilisez des noix ou des pignons de pin, ajoutez-les également à ce moment. Mixer : Une fois que les courgettes sont cuites, ajoutez-les dans le robot culinaire avec le mélange de persil. Mixez jusqu'à obtenir une consistance lisse ou légèrement texturée, selon votre préférence. Ajouter le fromage (facultatif) : Si vous choisissez d'utiliser du fromage, incorporez-le à la fin et pulsez brièvement pour le mélanger à la tartinade. Ajuster l'assaisonnement : Goûtez et ajustez l'assaisonnement avec du sel, du poivre, et peut-être un peu plus de jus de citron si nécessaire. Réfrigérer avant de servir : Transférez la tartinade dans un bol et couvrez-la. Réfrigérez pendant au moins une heure pour permettre aux saveurs de se mélanger. Servez frais.")
    ->setContent("Cette tartinade de courgettes et persil est délicieuse sur des tranches de baguette grillée, en sandwich, ou comme accompagnement pour des bâtonnets de légumes frais. Elle est non seulement savoureuse mais également saine et rafraîchissante.");

    $article8 = new Article();
    $article8
    ->setTitle("Pesto d'ail des Ours. ")
    ->setDescript("Voici une recette pour préparer un délicieux pesto d'ail des ours, parfait pour agrémenter vos pâtes, tartiner sur des toasts, ou comme condiment dans divers plats.")
    ->setPicture("ours.webp")
    ->setIngredient("Ingrédients : 100 g de feuilles d'ail des ours fraîches, 50 g de pignons de pin (ou de noix, pour une alternative), 50 g de parmesan râpé, 1 gousse d'ail (facultatif, selon votre goût), 150 ml d'huile d'olive de bonne qualité, Sel et poivre.")
    ->setPreparation("Préparation : Nettoyage des feuilles : Commencez par bien laver les feuilles d'ail des ours à l'eau froide pour enlever toute trace de terre ou de petits insectes. Séchez-les délicatement avec un torchon propre ou une essoreuse à salade. Torréfaction des pignons de pin : Dans une poêle sèche, faites griller légèrement les pignons de pin à feu moyen jusqu'à ce qu'ils soient dorés. Cela va exalter leur saveur. Laissez-les refroidir. Mélange des ingrédients : Dans le bol d'un robot culinaire, combinez les feuilles d'ail des ours, les pignons de pin refroidis, le parmesan râpé, et l'ail pelé si vous choisissez d'en utiliser. Mixez grossièrement. Ajout de l'huile d'olive : Tout en mixant, versez progressivement l'huile d'olive jusqu'à ce que le mélange forme une pâte homogène et lisse. Vous pouvez ajuster la quantité d'huile selon la consistance désirée. Assaisonnement : Assaisonnez avec du sel et du poivre au goût. Mixez encore brièvement pour intégrer les assaisonnements. Conservation : Transférez le pesto dans un bocal stérilisé et couvrez la surface du pesto avec un peu d'huile d'olive, cela aidera à conserver la fraîcheur et la couleur. Fermez le bocal et conservez au réfrigérateur.")
    ->setContent("Servez votre pesto d'ail des ours avec des pâtes, comme base pour une pizza, ou étalé sur des toasts pour un apéritif. Il est également délicieux mélangé à des vinaigrettes ou utilisé comme marinade pour des viandes ou des légumes grillés.");

    $article9 = new Article();
    $article9
    ->setTitle("Recette Tartinade de lentilles corail.")
    ->setDescript("La tartinade de lentilles corail est une recette simple et savoureuse, parfaite pour un apéritif sain ou un en-cas nutritif. Elle allie la douceur des lentilles corail à la fraîcheur du citron et des herbes aromatiques, créant ainsi une texture onctueuse et légèrement épicée. Cette tartinade est idéale pour être étalée sur des toasts croustillants ou des morceaux de légumes frais.")
    ->setPicture("lentilles.webp")
    ->setIngredient("Ingrédients : 200 g de lentilles corail, 1 gousse d'ail, 1 échalote, Le jus d'1 citron, 2 cuillères à soupe d'huile d'olive, 1 cuillère à café de cumin en poudre, 1 cuillère à café de paprika, Sel et poivre, Quelques brins de coriandre ou de persil frais.")
    ->setPreparation("Préparation : Rincer les lentilles : Commencez par bien rincer les lentilles corail sous l'eau froide jusqu'à ce que l'eau soit claire. Cuisson des lentilles : Mettez les lentilles dans une casserole et couvrez-les d'eau froide. Portez à ébullition, puis baissez le feu et laissez mijoter pendant environ 15 minutes, jusqu'à ce que les lentilles soient tendres. Égouttez les lentilles et laissez-les refroidir. Préparation des aromates : Pendant que les lentilles cuisent, pelez et hachez finement l'ail et l'échalote. Mélange des ingrédients : Dans un mixeur ou un robot culinaire, combinez les lentilles refroidies, l'ail, l'échalote, le jus de citron, l'huile d'olive, le cumin, le paprika, le sel et le poivre. Mixez jusqu'à obtenir une consistance lisse et homogène. Ajout des herbes : Ajoutez les herbes fraîches hachées et pulsez brièvement pour les incorporer sans les réduire en purée. Ajustement de la texture et des assaisonnements : Si la tartinade est trop épaisse, vous pouvez ajouter un peu d'eau ou d'huile d'olive pour ajuster la consistance. Goûtez et rectifiez l'assaisonnement si nécessaire. Réfrigération : Transférez la tartinade dans un bol et couvrez-la. Réfrigérez pendant au moins une heure avant de servir pour permettre aux saveurs de se mélanger.")
    ->setContent("Servez cette tartinade de lentilles corail sur des toasts, des crackers ou avec des bâtonnets de légumes frais. Elle peut également être utilisée comme garniture dans des wraps ou des sandwiches pour un repas léger et savoureux.");

    $article10 = new Article();
    $article10
    ->setTitle("Dahl de Lentilles.")
    ->setDescript("Le dahl de lentilles est un plat indien réconfortant et savoureux. C’est une sorte de ragoût épais composé de lentilles, généralement rouges ou jaunes, qui sont mijotées avec des épices comme le cumin, la coriandre, le curcuma et le garam masala. Souvent, des tomates, des oignons et de l'ail sont ajoutés pour la richesse des saveurs. Ce plat est non seulement délicieux et réchauffant mais aussi très nutritif, riche en protéines et en fibres. Il est habituellement servi avec du riz ou des naans pour un repas complet.")
    ->setPicture("dahl.webp")
    ->setIngredient("Ingrédients : 1 tasse de lentilles rouges, 1 gros oignon, haché, 2 gousses d'ail, émincées, 1 morceau de gingembre de 2 cm, râpé, 1 cuillère à café de cumin en poudre, 1 cuillère à café de coriandre en poudre, 1/2 cuillère à café de curcuma en poudre, 1/2 cuillère à café de garam masala, 1 pincée de piment rouge en poudre (facultatif), 2 tomates, coupées en dés, 3 tasses d'eau ou de bouillon de légumes, Sel au goût, Jus de 1/2 citron, Coriandre fraîche, hachée pour garnir, Huile végétale.")
    ->setPreparation("Instructions : Préparation des lentilles : Rincez les lentilles sous l'eau froide jusqu'à ce que l'eau soit claire. Faire revenir les épices : Dans une grande casserole, chauffez deux cuillères à soupe d'huile végétale. Ajoutez l'oignon, l'ail et le gingembre, et faites revenir jusqu'à ce que l'oignon soit translucide et doré. Ajouter les épices : Incorporez le cumin, la coriandre, le curcuma, le garam masala et le piment rouge. Faites cuire pendant une minute pour libérer les arômes. Cuire les lentilles : Ajoutez les lentilles, les tomates et l'eau ou le bouillon. Portez à ébullition, puis réduisez le feu et laissez mijoter à couvert pendant environ 20-25 minutes, ou jusqu'à ce que les lentilles soient tendres et le dahl épaissi. Assaisonner : Assaisonnez de sel et ajoutez le jus de citron. Mélangez bien. Servir : Servez chaud, garni de coriandre fraîche. Accompagnez de riz basmati ou de naans.")
    ->setContent("Ce dahl de lentilles est parfait pour un repas réconfortant. Il se conserve également très bien, les saveurs se développant encore plus après une nuit au réfrigérateur.");

    $article11 = new Article();
    $article11
    ->setTitle("Tartinade de Carottes Cumin et Citron.")
    ->setDescript("Voici une recette rafraîchissante de tartinade de carottes au cumin et citron, parfaite pour un apéritif léger ou une collation saine.")
    ->setPicture("cumin.webp")
    ->setIngredient("Ingrédients : 500 g de carottes, 2 cuillères à soupe d'huile d'olive, 2 gousses d'ail, 1 cuillère à café de cumin moulu, Le jus et le zeste d'1 citron, Sel et poivre, Quelques branches de coriandre ou de persil frais.")
    ->setPreparation("Préparation : Préparation des carottes : Pelez les carottes et coupez-les en rondelles. Faites-les cuire à la vapeur ou bouillies jusqu'à ce qu'elles soient bien tendres, environ 15-20 minutes. Cuisson des aromates : Pendant que les carottes cuisent, pelez et hachez finement les gousses d'ail. Faites-les revenir légèrement dans une poêle avec une cuillère à soupe d'huile d'olive, juste jusqu'à ce qu'ils soient parfumés. Mixer les ingrédients : Dans un mixeur ou un robot culinaire, placez les carottes cuites, l'ail revenu, le cumin, le jus et le zeste de citron, l'huile d'olive restante, le sel et le poivre. Mixez jusqu'à obtenir une consistance lisse. Ajout des herbes : Ajoutez les herbes fraîchement hachées au mélange et pulsez quelques fois pour les incorporer sans les broyer complètement. Ajustements : Goûtez la tartinade et ajustez les assaisonnements selon votre goût. Si la tartinade est trop épaisse, vous pouvez ajouter un peu d'eau ou d'huile d'olive pour la détendre. Réfrigération : Transférez la tartinade dans un contenant hermétique et laissez-la reposer au réfrigérateur pendant au moins une heure pour que les saveurs se mélangent bien.")
    ->setContent("Servez la tartinade de carottes au cumin et citron sur des toasts croustillants, des crackers, ou comme dip pour des crudités. Elle est également excellente utilisée comme condiment dans des wraps végétariens.");

    $article12 = new Article();
    $article12
    ->setTitle("Recette Houmous de Betterave.")
    ->setDescript("Voici une recette de houmous de betterave, un dip coloré et savoureux, parfait pour égayer vos apéritifs ou pour un en-cas sain.")
    ->setPicture("betterave.webp")
    ->setIngredient("Ingrédients : 400 g de pois chiches cuits et égouttés (environ une boîte), 200 g de betteraves cuites et pelées, 2 gousses d'ail, 2 cuillères à soupe de tahini (pâte de sésame), Le jus de 1 citron, 3 cuillères à soupe d'huile d'olive, Sel et poivre, Cumin en poudre (optionnel), Eau ou liquide de conservation des pois chiches pour ajuster la texture.")
    ->setPreparation("Préparation : Préparation des ingrédients : Si vous utilisez des pois chiches en conserve, rincez-les bien sous l'eau froide et égouttez-les. Assurez-vous que les betteraves sont cuites et tendres. Mixer les composants : Dans le bol d'un mixeur ou d'un robot culinaire, ajoutez les pois chiches, les betteraves coupées en morceaux, les gousses d'ail pelées, le tahini, le jus de citron, l'huile d'olive, un peu de sel, de poivre et une pincée de cumin si désiré. Mixez jusqu'à l'obtention d'une consistance lisse : Mixez tous les ingrédients jusqu'à ce que le mélange devienne lisse et homogène. Si le houmous est trop épais, ajoutez un peu d'eau ou du liquide de conservation des pois chiches, par petites quantités, jusqu'à obtenir la consistance désirée. Ajustement des saveurs : Goûtez le houmous et ajustez les assaisonnements selon votre goût, en ajoutant du sel, du poivre, ou plus de jus de citron si nécessaire. Réfrigération : Transférez le houmous dans un contenant hermétique et laissez-le reposer au réfrigérateur pendant au moins une heure pour permettre aux saveurs de se développer.")
    ->setContent("Servez le houmous de betterave bien frais, accompagné de pain pita chaud, de crackers, ou de légumes crus pour tremper. Il est aussi excellent comme garniture sur des sandwiches ou des wraps.");

    $article13 = new Article();
    $article13
    ->setTitle("Purée de Cabillaud a la Tomate et au Basilic")
    ->setDescript("Voici une recette de purée de cabillaud à la tomate et au basilic, idéale pour un repas léger et savoureux ou comme plat principal pour les enfants.")
    ->setPicture("cabillaud.webp")
    ->setIngredient("Ingrédients : 400 g de filets de cabillaud, 200 g de tomates pelées en dés (fraîches ou en conserve), 1 oignon moyen, 2 gousses d'ail, 10 feuilles de basilic frais, 2 cuillères à soupe d'huile d'olive, Sel et poivre, Un peu de lait ou de crème (facultatif, pour la consistance).")
    ->setPreparation("Préparation : Préparation des ingrédients : Commencez par hacher finement l'oignon et l'ail. Coupez les filets de cabillaud en gros morceaux. Cuisson du cabillaud : Dans une poêle, chauffez une cuillère à soupe d'huile d'olive à feu moyen. Ajoutez l'oignon et l'ail hachés et faites-les revenir jusqu'à ce qu'ils deviennent translucides. Ajoutez ensuite les morceaux de cabillaud et laissez cuire environ 5 minutes, jusqu'à ce que le poisson soit presque cuit. Ajout des tomates et du basilic : Incorporez les tomates en dés et la moitié des feuilles de basilic hachées. Assaisonnez avec du sel et du poivre. Couvrez et laissez mijoter pendant 10 minutes, en remuant occasionnellement. Mixer la préparation : Une fois que le poisson est bien cuit et que les saveurs se sont mélangées, retirez du feu et laissez légèrement refroidir. Transférez le mélange dans un mixeur ou utilisez un mixeur plongeant pour puréer le tout jusqu'à obtenir une consistance lisse. Pour une purée plus onctueuse, vous pouvez ajouter un peu de lait ou de crème à ce stade. Ajustement des saveurs et finitions : Goûtez la purée et ajustez les assaisonnements si nécessaire. Ajoutez le reste des feuilles de basilic frais hachées pour un goût plus prononcé. Réchauffage : Réchauffez la purée à feu doux si nécessaire avant de servir.")
    ->setContent("Servez la purée de cabillaud à la tomate et au basilic bien chaude. Elle peut être accompagnée de riz blanc, de pâtes, ou de légumes vapeur pour un repas complet. Cette purée est aussi parfaitement adaptée pour les bébés et les jeunes enfants, offrant une façon délicieuse et nutritive de leur faire découvrir le poisson. Ce plat combine la douceur du cabillaud avec l'acidité des tomates et la fraîcheur du basilic, créant une harmonie de saveurs qui plaît généralement à toute la famille. Bon appétit !");

    $article14 = new Article();
    $article14
    ->setTitle("La purée de pommes de terre au gingembre.")
    ->setDescript("La purée de pommes de terre au gingembre est une variante savoureuse et légèrement épicée de la classique purée de pommes de terre. Le gingembre ajoute une note piquante qui réveille les saveurs, la rendant idéale pour accompagner des plats de viande ou de poisson. Voici comment préparer cette délicieuse purée.")
    ->setPicture("gingembre.webp")
    ->setIngredient("Ingrédients : 1 kg de pommes de terre (de préférence des variétés farineuses comme les Russet ou les Bintje), 2 à 3 cuillères à soupe de beurre, 1/2 tasse (120 ml) de lait ou de crème, 1 cuillère à soupe de gingembre frais, finement râpé, Sel et poivre au goût.")
    ->setPreparation("Instructions : Préparer les pommes de terre : Épluchez les pommes de terre et coupez-les en morceaux de taille égale pour assurer une cuisson uniforme. Cuire les pommes de terre : Placez les morceaux de pommes de terre dans une grande casserole d'eau froide salée. Portez à ébullition, puis réduisez le feu et laissez mijoter jusqu'à ce que les pommes de terre soient tendres lorsqu'elles sont piquées avec une fourchette, environ 15 à 20 minutes. Chauffer le lait et le beurre : Pendant que les pommes de terre cuisent, chauffez doucement le lait ou la crème avec le beurre dans une petite casserole jusqu'à ce que le beurre soit fondu. Ajoutez le gingembre râpé et laissez infuser à feu doux. Égoutter et écraser les pommes de terre : Une fois les pommes de terre cuites, égouttez-les bien et remettez-les dans la casserole. Écrasez les pommes de terre avec un presse-purée jusqu'à obtenir la consistance désirée. Incorporer le mélange de lait : Ajoutez progressivement le mélange de lait chaud et de beurre aux pommes de terre écrasées, en mélangeant jusqu'à ce que la purée soit lisse et crémeuse. Assaisonnez de sel et de poivre au goût. Servir : Servez la purée de pommes de terre au gingembre bien chaude, garnie d'un peu de beurre supplémentaire si désiré.")
    ->setContent("Cette purée de pommes de terre au gingembre est excellente avec des rôtis, du poisson grillé ou même comme base pour des plats végétariens. Le gingembre ajoute une touche exotique qui peut transformer un repas ordinaire en un festin spécial.");

    $article15 = new Article();
    $article15
    ->setTitle("Compote à la Mangue et à la Banane.")
    ->setDescript("La compote de mangue et banane est une recette simple et délicieuse, parfaite pour un dessert léger ou comme accompagnement pour des plats de petit déjeuner. Voici comment la préparer.")
    ->setPicture("mangue.webp")
    ->setIngredient("Ingrédients : Mangues : 2 grosses mangues mûres, pelées et coupées en dés, Bananes : 2 grandes bananes, pelées et tranchées, Jus de citron : 1 cuillère à soupe pour éviter que les bananes ne brunissent, Sucre (facultatif) : 2 cuillères à soupe, ajustez selon votre goût, Eau : ¼ de tasse (ou plus, selon la consistance désirée), Cannelle (facultatif) : 1/2 cuillère à café pour une note épicée.")
    ->setPreparation("Instructions : Préparation des fruits : Dans un grand bol, mélangez les fruits coupés avec le jus de citron. Si vous utilisez du sucre, ajoutez-le à cette étape pour qu'il se dissolve bien avec le jus des fruits. Cuisson : Transférez les fruits dans une casserole et ajoutez l'eau. Portez à ébullition à feu moyen. Une fois à ébullition, réduisez le feu et laissez mijoter pendant environ 10-15 minutes, ou jusqu'à ce que les fruits soient tendres et que le mélange commence à épaissir. Pour une compote avec des morceaux, laissez les fruits cuire jusqu'à ce qu'ils soient juste tendres. Pour une compote lisse, prolongez la cuisson jusqu'à ce que les fruits se désagrègent complètement. Mixer (optionnel) : Pour une texture plus lisse, utilisez un mixeur plongeant ou transférez le mélange dans un mixeur pour le réduire en purée lisse. Ajout d'épices : Si vous aimez, saupoudrez de cannelle juste avant de servir ou pendant la cuisson pour infuser la saveur. Refroidissement et service : Laissez refroidir la compote à température ambiante, puis réfrigérez-la. Servez froid ou à température ambiante, selon votre préférence.")
    ->setContent("Cette compote peut être servie seule, avec du yaourt, du porridge, ou utilisée comme garniture pour des crêpes ou des gaufres. Bon appétit!");

    $manager->persist($article1);
    $manager->persist($article2);
    $manager->persist($article3);
    $manager->persist($article4);
    $manager->persist($article5);
    $manager->persist($article6);
    $manager->persist($article7);
    $manager->persist($article8);
    $manager->persist($article9);
    $manager->persist($article10);
    $manager->persist($article11);
    $manager->persist($article12);
    $manager->persist($article13);
    $manager->persist($article14);
    $manager->persist($article15);
    $manager->flush();
}
  
}
